version: '3.3'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:v3.2.2

    ports:
    - "3000:3000"
    - "5000:5000"

    env_file:
      - ./confs/tyk_analytics.env

    networks:
    - tyk

  tyk-gateway:
    image: tykio/tyk-gateway:v3.2.2

    ports:
    - "8080:8080"

    volumes:
    - ./middleware:/opt/tyk-gateway/middleware

    env_file:
      - ./confs/tyk.env

    networks:
    - tyk

  tyk-pump:
    image: tykio/tyk-pump-docker-pub:v1.5.1-rc2

    env_file:
      - ./confs/pump.env

    networks:
    - tyk

  tyk-redis:
    image: redis

    ports:
    - "6379:6379"

    volumes:
    - redis-data:/data

    networks:
    - tyk

  tyk-mongo:
    image: mongo:3.2
    command: ["mongod", "--smallfiles"]

    ports:
    - "27017:27017"

    volumes:
    - mongo-data:/data/db

    networks:
    - tyk

volumes:
  redis-data:
  mongo-data:

networks:
  tyk:
