version: '3.9'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:v5.3.1
    environment:
      - TYK_DB_LICENSEKEY=${DASH_LICENSE:?License key missing from Docker environment file "".env" file.  Review The Getting Started steps in README.md.}
      - TYK_DB_STORAGE_MAIN_TYPE=postgres
      - TYK_DB_STORAGE_MAIN_CONNECTIONSTRING=user=postgres password=topsecretpassword host=tyk-postgres port=5432 database=tyk_analytics
    depends_on:
      tyk-postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - ./confs/tyk_analytics.env
    networks:
      - tyk
  
  tyk-ent-portal:
    image: tykio/portal:v1.9.0
    command: --bootstrap
    ports:
      - 3001:3001
    environment:
      - PORTAL_LICENSEKEY=${DASH_LICENSE:?License key missing from Docker environment file "".env" file.  Review The Getting Started steps in README.md.}
    env_file:
      - ./confs/tyk_portal.env
    networks:
      - tyk

  tyk-gateway:
    image: tykio/tyk-gateway:v5.3.1
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - ./confs/tyk.env
    volumes:
      - ./confs/tyk.conf:/opt/tyk-gateway/tyk.conf
    networks:
      - tyk
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tyk-pump:
    image: tykio/tyk-pump-docker-pub:v1.9.0
    env_file:
      - ./confs/pump.env
      - ./confs/pump.postgres.env
    depends_on:
      tyk-postgres:
        condition: service_healthy
    networks:
      - tyk

  tyk-redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - tyk

  tyk-postgres:
    image: postgres:latest

    environment:
      - POSTGRES_DB=tyk_analytics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=topsecretpassword

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - tyk

  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=ataimo@tyk.io
      - RABBITMQ_DEFAULT_PASS=alex1234.
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - tyk
  
volumes:
  redis-data:
  postgres-data:

networks:
  tyk:
