version: '3.9'
services:
  tyk-dashboard:
    environment:
      - TYK_DB_STORAGE_MAIN_TYPE=postgres
      - TYK_DB_STORAGE_MAIN_CONNECTIONSTRING=user=postgres password=topsecretpassword host=tyk-postgres port=5432 database=tyk_analytics
    depends_on:
      tyk-postgres:
        condition: service_healthy

  tyk-pump:
    env_file:
      - ./confs/pump.postgres.env
    depends_on:
      tyk-postgres:
        condition: service_healthy
      
  tyk-postgres:
    image: postgres:latest
    container_name: tyk-postgres

    environment:
      - POSTGRES_DB=tyk_analytics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=topsecretpassword

    ports:
      - "5432:5432"

    volumes:
      - db-data:/data/db

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - tyk
      
  tyk-mongo:
    entrypoint: ["echo", "Docker Mongo service disabled. Using Postgres service instead.", ""]
    command: []
